name: elastic_service_compose

services:
  elastic_app:
    container_name: elastic-service
    build: .

    ports:
      - "9901:9901"
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
  elasticsearch:
    container_name: elasticsearch-storage
    image: elasticsearch:8.19.18
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    healthcheck:
      test: [ "CMD-SHELL", "curl -fs http://localhost:9200 >/dev/null || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 12