spring.application.name=elastic-search-service
server.servlet.context-path=/elastic-search-service
server.port=9901

spring.kafka.bootstrap-servers=localhost:9094

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3

spring.elasticsearch.uris=http://localhost:9200